services:
  - type: web
    name: webrtc-snapshot-render
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # default upload can be set here; UI can override
      - key: UPLOAD_URL
        value: https://practice-8waa.onrender.com/upload
    healthCheckPath: /status
